# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d42cf6bdbdcd6bbe397022d8e4d11a5335e23975e29740993716ff5de17ed79e17907a169dfc36e43f5bd2b75aba8d838610dd69de51e422693fad4e2282f567

test:
  secret_key_base: a2da1f24fab3a586e5ef2e5f12a041eed3cb4b7bd2846191735a1d4dbfee6bf76f9e4fc02d53630f42c8430b63638798388ff51526313238899fc4f45a06570d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
